# Generated by Django 2.2.28 on 2023-11-25 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppPC360', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPC360.Item')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
