# Generated by Django 2.2.28 on 2023-11-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPC360', '0002_auto_20231125_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='E',
            new_name='ItemState',
        ),
    ]
