# Generated by Django 2.2.28 on 2023-11-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPC360', '0003_auto_20231125_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemstate',
            old_name='fecha_cambio',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='itemstate',
            old_name='estado',
            new_name='state',
        ),
    ]
