# Generated by Django 2.2.28 on 2023-11-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPC360', '0005_auto_20231126_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemstate',
            name='item',
        ),
    ]
