# Generated by Django 2.2.28 on 2023-11-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPC360', '0006_remove_itemstate_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstate',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPC360.Item'),
        ),
    ]
