# Generated by Django 2.2.28 on 2023-11-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPC360', '0007_itemstate_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemState',
        ),
    ]
