# Generated by Django 2.2.28 on 2023-11-27 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppPC360', '0008_delete_itemstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('action', models.CharField(max_length=100)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPC360.Item')),
            ],
        ),
    ]
