# Generated by Django 2.2.28 on 2023-11-30 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPC360', '0009_itemstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='create_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
