# Generated by Django 2.2.28 on 2023-12-10 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPC360', '0011_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
