# Generated by Django 2.2.28 on 2023-12-10 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppPC360', '0012_auto_20231210_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstate',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
