# Generated by Django 2.2.28 on 2023-12-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPC360', '0013_auto_20231210_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
